import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import Link from "next/link"; // Used for client-side navigation between pages
import "./globals.css";


const geistSans = Playfair_Display({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ================= HEADER ================= */}
        <header className="bg-[#f4efe8]">
          <nav
            className="
      max-w-7xl
      mx-auto
      px-10
      py-[10px_35px]   
      flex
      justify-between
      items-center
    "
      >
            {/* Site title Link → clicking logo goes to Home page  */}
            <Link href="/" className="text-2xl font-serif text-[#350905] hover:text-[#8a6a3d] transition">
              Dr. Maya Reynolds, PsyD
            </Link>

            {/* Navigation links */}
            <div className="flex gap-8 text-sm font-serif text-[#350905] ">
              <Link href="/blog">Blog</Link>
              <Link href="/contact">Contact</Link>
            </div>
          </nav>
        </header>

        {/* ================= PAGE CONTENT ================= */}
        {/* Each page.tsx will render HERE */}
        <main>{children}</main>

       {/* FOOTER */}
<footer className="bg-[#f4f1e3] font-serif text-[#350905] pt-12">
  <div className="max-w-5xl mx-auto px-6 pb-8">

    {/* Main Layout */}
    <div className="grid md:grid-cols-3 gap-10">

      {/* LEFT COLUMN */}
      <div>
        <h3 className="text-2xl font-semibold leading-snug">
          Dr. Maya Reynolds, PsyD
        </h3>
        <p className="mb-3 text-sm">
          Licensed Clinical Psychologist
        </p>

        <p className="text-sm">123th Street 45 W</p>
        <p className="mb-3 text-sm">Santa Monica, CA 90401</p>

        <p className="text-sm mb-1">
          maya@mayareynolds.com
        </p>
        <p className="text-sm">
          (310)555-1234
        </p>
      </div>

      {/* QUICK LINKS */}
      <div>
        <h4 className="text-lg text-center font-semibold mb-3">QUICK LINKS</h4>

        <ul className="space-y-1 text-center">
          <li><a href="/" className="hover:opacity-70 transition">Home</a></li>
          <li><a href="/#about" className="hover:opacity-70 transition">About</a></li>
          <li><a href="/#services" className="hover:opacity-70 transition">Services</a></li>
          <li><a href="/contact" className="hover:opacity-70 transition">Contact</a></li>
          <li><a href="/blog" className="hover:opacity-70 transition">Blog</a></li>
        </ul>
      </div>

      {/* HOURS */}
      <div>
        <h4 className="text-lg text-end font-semibold mb-3">HOURS</h4>

        <p className="text-sm text-end">Monday – Friday</p>
        <p className="text-sm mb-2 text-end">10:00 AM – 6:00 PM</p>

        <p className="text-sm text-end">Saturday</p>
        <p className="text-sm mb-2 text-end">By appointment</p>

        <p className="text-sm text-end">
          Telehealth available<br />
          throughout California
        </p>
      </div>

      

    </div>
  </div>

  {/* Bottom Bar */}
  <div className="border-t border-[#d8d2c7] py-4 text-center text-xs leading-relaxed">
    <div className="flex justify-center gap-6 mb-2">
      <a href="#" className="hover:opacity-70 transition">Privacy Policy</a>
      <a href="#" className="hover:opacity-70 transition">Terms of Service</a>
      <a href="#" className="hover:opacity-70 transition">Disclaimer</a>
    </div>

    <p>
      © 2026 Dr. Maya Reynolds, PsyD. All rights reserved. | Built for Healing
    </p>
  </div>
</footer>

      </body>
    </html>
  );
}
