import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import Link from "next/link"; // Used for client-side navigation between pages
import "./globals.css";


const geistSans = Playfair_Display({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ================= HEADER ================= */}
        <header className="bg-[#f4efe8]">
          <nav
            className="
      max-w-7xl
      mx-auto
      px-10
      py-[10px_35px]   
      flex
      justify-between
      items-center
    "
      >
            {/* Site title Link → clicking logo goes to Home page  */}
            <Link href="/" className="text-2xl font-serif text-[#350905] hover:text-[#8a6a3d] transition">
              Dr. Maya Reynolds, PsyD
            </Link>

            {/* Navigation links */}
            <div className="flex gap-8 text-sm font-serif text-[#350905] ">
              <Link href="/blog">Blog</Link>
              <Link href="/contact">Contact</Link>
            </div>
          </nav>
        </header>

        {/* ================= PAGE CONTENT ================= */}
        {/* Each page.tsx will render HERE */}
        <main>{children}</main>

        {/* FOOTER */}
        <footer className="bg-[#fbf7f1] pt-24">
          {/* Outer container */}
          <div className="max-w-7xl mx-auto px-8 pb-20">
            {/* 
      flex → horizontal layout
      justify-between → left content stays left, right content stays right
    */}
            <div className="flex flex-col md:flex-row justify-between gap-16">
              {/* LEFT COLUMN — BRAND + CONTACT */}
              <div>
                <h3 className="text-2xl font-semibold mb-6">Dr. Maya Reynolds, PsyD</h3>

                <p className="mb-2">123 Example Road</p>
                <p className="mb-4">Minneapolis, MN</p>

                <p className="underline mb-2">email@example.com</p>
                <p className="underline">(555) 555-5555</p>
              </div>

              {/* RIGHT SIDE — HOURS + FIND */}
              <div className="flex gap-24">
                {/* 
          gap-24 → space between Hours and Find
        */}

                {/* HOURS COLUMN */}
                <div>
                  <h4 className="text-xl font-semibold mb-6">Hours</h4>

                  <p className="mb-2">Monday – Friday</p>
                  <p>10am – 6pm</p>
                </div>

                {/* FIND COLUMN */}
                <div>
                  <h4 className="text-xl font-semibold mb-6">Find</h4>

                  <ul className="space-y-2 underline">
                    <li>
                      <a href="/">Home</a>
                    </li>
                    <li>
                      <a href="/contact">Contact</a>
                    </li>
                    <li>
                      <Link href="/blog">Blog</Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          {/* BOTTOM FOOTER BAR */}
          <div className="bg-[#e8e3db] py-10 text-center text-sm">
            <div className="flex flex-wrap justify-center gap-6 underline mb-6">
              <a href="#">Privacy & Cookies Policy</a>
              <a href="#">Good Faith Estimate</a>
              <a href="#">Website Terms & Conditions</a>
              <a href="#">Disclaimer</a>
            </div>

            <p className="mb-4">
              Website Template Credits:{" "}
              <span className="underline">Go Bloom Creative</span>
            </p>

            <p>All Rights Reserved © 2024 Your Business Name Here, LLC.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
